[/Script/Engine.InputSettings]
; Commandes classiques (sans fichiers d'actions à créer dans l'éditeur).
DefaultPlayerInputClass=/Script/Engine.PlayerInput
DefaultInputComponentClass=/Script/Engine.InputComponent
+AxisMappings=(AxisName="MoveForward",Scale=1.000000,Key=W)
+AxisMappings=(AxisName="MoveForward",Scale=1.000000,Key=Z)
+AxisMappings=(AxisName="MoveForward",Scale=-1.000000,Key=S)
+AxisMappings=(AxisName="MoveRight",Scale=1.000000,Key=D)
+AxisMappings=(AxisName="MoveRight",Scale=-1.000000,Key=A)
+AxisMappings=(AxisName="MoveRight",Scale=-1.000000,Key=Q)
+AxisMappings=(AxisName="MoveForward",Scale=1.000000,Key=Gamepad_LeftY)
+AxisMappings=(AxisName="MoveRight",Scale=1.000000,Key=Gamepad_LeftX)
+AxisMappings=(AxisName="Turn",Scale=1.000000,Key=MouseX)
+AxisMappings=(AxisName="LookUp",Scale=-1.000000,Key=MouseY)
+AxisMappings=(AxisName="TurnRate",Scale=1.000000,Key=Gamepad_RightX)
+AxisMappings=(AxisName="LookUpRate",Scale=-1.000000,Key=Gamepad_RightY)
+ActionMappings=(ActionName="Run",Key=LeftShift)
+ActionMappings=(ActionName="Run",Key=Gamepad_LeftThumbstick)
+ActionMappings=(ActionName="CameraShoulder",Key=One)
+ActionMappings=(ActionName="CameraWide",Key=Two)
+ActionMappings=(ActionName="CameraFirst",Key=Three)
+ActionMappings=(ActionName="CameraCycle",Key=V)
+ActionMappings=(ActionName="CameraCycle",Key=Gamepad_RightThumbstick)
+ActionMappings=(ActionName="SwapShoulder",Key=Tab)
+ActionMappings=(ActionName="ActPhoto",Key=F)
+ActionMappings=(ActionName="ActPhoto",Key=Gamepad_FaceButton_Left)
+ActionMappings=(ActionName="ActCrier",Key=C)
+ActionMappings=(ActionName="ActCrier",Key=Gamepad_FaceButton_Top)
+ActionMappings=(ActionName="ActEnvoyer",Key=E)
+ActionMappings=(ActionName="ActEnvoyer",Key=Gamepad_FaceButton_Right)
+ActionMappings=(ActionName="Rappel",Key=R)
+ActionMappings=(ActionName="Appel17",Key=T)
+ActionMappings=(ActionName="Save",Key=F5)
+ActionMappings=(ActionName="Carnet",Key=J)
+ActionMappings=(ActionName="Carnet",Key=Gamepad_Special_Left)
+AxisMappings=(AxisName="Zoom",Scale=1.000000,Key=MouseWheelAxis)
+ActionMappings=(ActionName="Rappel",Key=Gamepad_LeftShoulder)
+ActionMappings=(ActionName="Reste",Key=X)
+ActionMappings=(ActionName="Reste",Key=Gamepad_DPad_Down)
+ActionMappings=(ActionName="Cherche",Key=G)
+ActionMappings=(ActionName="Cherche",Key=Gamepad_RightShoulder)
+ActionMappings=(ActionName="Pause",Key=P)
+ActionMappings=(ActionName="Pause",Key=Escape)
+ActionMappings=(ActionName="Pause",Key=Gamepad_Special_Right)
+ActionMappings=(ActionName="Inventaire",Key=I)
+ActionMappings=(ActionName="Inventaire",Key=Gamepad_DPad_Up)
+ActionMappings=(ActionName="Telephone",Key=O)
+ActionMappings=(ActionName="Telephone",Key=Gamepad_DPad_Left)
+ActionMappings=(ActionName="Lampe",Key=L)
+ActionMappings=(ActionName="Lampe",Key=Gamepad_DPad_Right)
+ActionMappings=(ActionName="Load",Key=F9)
+ActionMappings=(ActionName="Montre",Key=M)
+ActionMappings=(ActionName="Non",Key=N)
+ActionMappings=(ActionName="Bravo",Key=B)
+ActionMappings=(ActionName="VaLaBas",Key=K)
